#!/bin/bash
sudo docker run -d \
	--name jenkins-master \
	--mount source=jenkins-log,target=/var/log/jenkins \
	--mount source=jenkins-data,target=/var/jenkins_home \
	-p 8089:8080 -p 50009:50000 \
	jenkins-mr
